name: sub3
description: "Sub3 - Indoor Running Zapp for treadmill runners."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_blue_plus: ^1.35.2
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8
  xml: ^6.5.0
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  flutter_dotenv: ^6.0.0
  flutter_web_auth_2: ^5.0.1
  flutter_secure_storage: ^10.0.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
